---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt: 
    update_cache: yes 
    name: ["docker-ce"]
    state: latest
    install_recommends: yes

- name: "Start Docker Service"
  ansible.builtin.service:
    name: docker
    state: started

# - name: Pull Docker image
#   docker_image:
#     name: "{{ dockerimage }}"
#     source: pull

# - name: Create container
#   docker_container:
#     name: "{{ containername }}"
#     image: "{{ dockerimage }}"
#     published_ports: [8000:8000]
#     state: present

- name: download and install minikube
  become: yes
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube

- name: start minikube
  # become: yes
  shell: |
    minikube start --driver=docker

# - name: Download and install kubectl
#   become: yes
#   shell: |
#     minikube kubectl -- get po -A

- name: download and install kubectl
  become: yes
  shell: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    install kubectl /usr/local/bin/kubectl

- name: Deploy docker container
  become: yes
  shell: |
    kubectl create deployment hello-world --image={{ dockerimage }}
    kubectl port-forward service/hello-world 8000:8000