version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.0

commands:
  destroy-environment:
    description: Destroy cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name capstone-${CIRCLE_WORKFLOW_ID}
  setup-rust-nightly:
    description: Use Rust nightly as required by Rocket framework
    steps:
      - run:
          name: set rust version default to nightly
          command: rustup default nightly

# rust circleci setup gleaned from https://gist.github.com/LukeMathWalker/6153b07c4528ca1db416f24b09038fca
jobs:
  build-and-test:
    docker:
      - image: circleci/rust
    environment:
      # Fail the build if there are warnings
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - setup-rust-nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: |
            cd hello_world
            cargo generate-lockfile
      # - restore_cache:
      #     keys:
      #       - cache-{{ arch }}-<< pipeline.id >>
      - run:
          name: Build all targets
          command: |
            cd hello_world
            cargo build
      # - save_cache:
      #     paths:
      #       - /usr/local/cargo/registry
      #       - hello_world/target/debug/.fingerprint
      #       - hello_world/target/debug/build
      #       - hello_world/target/debug/deps
      #       - hello_world/target/debug/hello_world
      #     key: cache-{{ arch }}-<< pipeline.id >>
      - run:
          name: Run all tests
          command: |
            cd hello_world
            cargo test

  security:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - setup-rust-nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Cache permission
          command: |
            sudo chown -R $(whoami):$(id -ng) /usr/local/cargo
      # - restore_cache:
      #     keys:
      #       - v1-cargo-audit-{{ arch }}-${CIRCLE_WORKFLOW_ID}
      - run:
          name: Install dependency auditing tool
          command: cargo install cargo-audit
      # - save_cache:
      #     paths:
      #       - /usr/local/cargo
      #     key: v1-cargo-audit-{{ arch }}-${CIRCLE_WORKFLOW_ID}
      - run:
          name: Check for known security issues in dependencies
          command: |
            cd hello_world
            cargo audit

  format:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - setup-rust-nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install formatter
          command: rustup component add rustfmt
      - run:
          name: Formatting
          command: |
            cd hello_world
            cargo fmt --all -- --check

  lint:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - setup-rust-nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          name: Linting
          command: |
            cd hello_world
            cargo clippy -- -D warnings
  
  build-final:
    docker:
      - image: circleci/rust
    environment:
      # Fail the build if there are warnings
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - setup-rust-nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: |
            cd hello_world
            cargo generate-lockfile
      # - restore_cache:
      #     keys:
      #       - build-cache-{{ arch }}-<< pipeline.id >>
      - run:
          name: Build all targets
          command: |
            cd hello_world
            rustup target add x86_64-unknown-linux-gnu
            cargo build --target=x86_64-unknown-linux-gnu --release
      - save_cache:
          paths:
            - hello_world/target/x86_64-unknown-linux-gnu/release/hello_world
          key: build-cache-{{ arch }}-<< pipeline.id >>


  build-image:
    docker:
      - image: docker:git
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ arch }}-<< pipeline.id >>
      - setup_remote_docker
          # Layer caching requires paid CircleCI account
          #docker_layer_caching: true
      - run:
          name: build and push Docker image
          command: |
            pwd
            ls -al
            docker build --tag=$DOCKER_USER/udacity-cloud-devops-engineer-capstone .
            imageID=$(docker image ls | grep 'udacity-cloud-devops-engineer-capstone' | awk '{print $3}')
            docker image ls
            echo "I think the image ID I just built is $imageID"
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
            docker tag $imageID $DOCKER_USER/udacity-cloud-devops-engineer-capstone:${CIRCLE_WORKFLOW_ID}
            docker tag $imageID $DOCKER_USER/udacity-cloud-devops-engineer-capstone:latest
            docker push $DOCKER_USER/udacity-cloud-devops-engineer-capstone:${CIRCLE_WORKFLOW_ID}

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
      - security
      - format
      - lint
      - build-final:
          requires: [build-and-test, security, format, lint]
      - build-image:
          requires: [build-final]
      # - deploy-infra:
      #     requires: [build-image]
      # - deploy-image:
      #     requires: [deploy-infra]
      # - smoke-test:
      #     requires: [deploy-image]
      # - cloudfront-update:
      #     requires: [smoke-test] 
      #     filters:
      #       branches:
      #         only: [master]

