Description: >
  Udacity Cloud DevOps Engineer Capstone stack.

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub capstone-${WorkflowID}
      GroupDescription: Allow port 8000 and 22.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 127.0.0.1/32

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # InstanceType: t2.micro
      InstanceType: t2.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-0ca5c3bd5a268e7db 
      Tags:
        - Key: Name
          Value: !Sub capstone-${WorkflowID}

Outputs:
  WorkflowID:
    Description: The workflow ID to identify this stack
    Value: !Sub "${WorkflowID}"