---

- name: Blue Green deploy
  shell: |
    export BLUE=$(kubectl get svc | grep 8000: | grep -v "{{ WORKFLOW_ID }}"| awk '{print $1}')
    export GREEN={{ containername }}
    kill $(ps aux | grep "port-forward" | grep "8000:8000" | grep "$BLUE" | awk '{print $2}')
    nohup kubectl port-forward --address 0.0.0.0 service/$GREEN 8000:8000 > /dev/null &
    kubectl delete deployment $BLUE
    kubectl delete service $BLUE
    kill $(ps aux | grep "port-forward" | grep "8001:8000" | grep "$GREEN" | awk '{print $2}') # this is the non-production port on 8001 that we used for smoke testing

- name: Making sure we didn't break it
  shell: |
    curl http://localhost:8000